### ISSUE TITLE
Rework pipelines to start with numbers

### ISSUE THREAD

**Issue by philippkahr** [enotspe/fortinet-2-elasticsearch#1]
Hi,

I think it is hard to know what and when which pipeline will be run. I suggest the following architecture for logstash:

```
10-input.conf
20-enhancement.conf
30-filter.conf
50-dootherstuff.conf
90-output.conf
```

then it is more easy to quickly understand how those pipelines are working together.

**Comment by enotspe** [comment]
@philippkahr 
thanks for the suggestion. you are right!!!

we will update it as suggested.
