### ISSUE TITLE
[Question] Is remove_field useful ?

### ISSUE THREAD

**Issue by Whysmerhill** [enotspe/fortinet-2-elasticsearch#13]
Hello,

I'm new to logstash, so forgive me if my question is stupid.
But what is the purpose of this line (file 40-fortigate_2_ecs, line 49) : 
` remove_field => [ "agent", "error", "file", "group", "hash", "host", "interface", "log", "process", "server", "service", "url", "user" ]`
The previous rename is replacing the select fields anyway ? No ? 

Best regards,

**Comment by enotspe** [comment]
You are totally right!!!

But we had many issues with over overlapping fields, so we leave there to be 200% sure it will work.
