### ISSUE TITLE
Fortigate logs to Elastic SIEM App

### ISSUE THREAD

**Issue by H1L021** [enotspe/fortinet-2-elasticsearch#16]
Hello,
ECS version: 1.5
Elastic stack 7.6.2

I don't know why I am finding this repo until today, such a great work. 
I haven't tried this mapping yet since I created my own but I noticed that if you want this to work with Elastic SIEM to have a more complete and centralized visibility with other firewall/endpoint logs, you would need to change/add few things : 

- The **Timeline Event Renderer** won't give you this view : 

![image](https://user-images.githubusercontent.com/18106793/81352955-5ce2be00-90b7-11ea-8e30-39bd4aa00c02.png)

Instead you would have flat events. This is because of the `even.category` is set to `network` even though that this is what is recommended in the documentation but I had to change it to `network_traffic` to get the event renderer working for my fortigate logs.

More info in this reddit thread [here](https://www.reddit.com/r/elasticsearch/comments/ftmxjj/how_to_obtain_this_kind_of_view_in_siem_app/)
- If you want to see top source and destination countries on the Network panel of your Elastic SIEM app you would need to use the GeoIP processor of an ingest node and not logstash, since the one logstash uses is not ecs friendly because it creates a `country_code1` or `country_code2`... etc instead of `country_iso_code` which the one inspected by Elastic SIEM . From the kibana developper panel create an ingest pipeline :

```
PUT _ingest/pipeline/geoip-info-fortinet
{
    "description": "Add geoip info",
    "processors": [
        {
            "geoip": {
                "field": "srcip",
                "target_field": "source.geo"
            }
        },
        {
            "geoip": {
                "field": "dstip",
                "target_field": "destination.geo"
            }
        }
    ]
}
```
Make sure that the node you creating this into is an `node.ingest : true `

Hope it helps someone and thanks for the great work.

**Comment by enotspe** [comment]
Hi @H1L021 , thanks for the suggestion for `network_traffic `!!! I spent quite some time trying to figure out how to make it work on SIEM. I will add it to `even.category` as suggested

About geo field names, the pipeline [geo_enrichment](https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/logstash/50-geo_enrichment) already handles it so those fields show up on SIEM UI.

```
    #rename iso code fields to match ECS
    mutate { 
        remove_field => ["src_ip_geo_apply", "dest_ip_geo_apply" ] 
        rename => { "[source][geo][country_code2]" => "[source][geo][country_iso_code]" }
        rename => { "[destination][geo][country_code2]" => "[destination][geo][country_iso_code]" }
        rename => { "[source][geo][region_code]" => "[source][geo][region_iso_code]" }
        rename => { "[destination][geo][region_code]" => "[destination][geo][region_iso_code]" }
```

**Comment by H1L021** [comment]
Thank you, my bad didn't see it. Sorry

**Comment by enotspe** [comment]
https://github.com/enotspe/fortinet-2-elasticsearch/commit/3af76bdda5e8f8d7bf5571082180964d19f5eba6

**Comment by fredtj** [comment]
looks like network_traffic is depreciated as of 8.0.0 - see here [https://github.com/elastic/beats/issues/19039](https://github.com/elastic/beats/issues/19039)

perhaps the real issue is the timeline event renderer needs to be updated?

**Comment by enotspe** [comment]
yeah. That is why I left this line commented

https://github.com/enotspe/fortinet-2-elasticsearch/blob/7ee2df82e11ba9ea590cda9e7f35e217ff133157/logstash/40-fortigate_2_ecs#L142
