### ISSUE TITLE
Can a condition work inside of a filter ?

### ISSUE THREAD

**Issue by H1L021** [enotspe/fortinet-2-elasticsearch#17]
https://github.com/enotspe/fortinet-2-elasticsearch/blob/bb10df13798f1aed442d021a96e88a1136dc7482/logstash/40-fortigate_2_ecs#L209

**Comment by enotspe** [comment]
hi, you are totally right. This is a mistake from my side. I realized yesterday and corrected it on my own pipeline, I have added some other enhacements, mostrly regarding ecs categorization fields for type=utm. I will be uploading the corrected version this week. Let´s keep this issue open until then.

**Comment by enotspe** [comment]
changes on 9cd82df223ed9e996e04ebf9d3faf0bd67c3f716 correct that error
