### ISSUE TITLE
yml files

### ISSUE THREAD

**Issue by secufred** [enotspe/fortinet-2-elasticsearch#2]
Hi, 

could you publish a sampe of the the yml files used ? ( 2 entries per file would be great )

**Comment by enotspe** [comment]
yes, we will be updating pipelines and other files in a few weeks. We will include yml files as well

**Comment by wkyrlach** [comment]
Thanks! Also an issue for me as well! Much appreciated.

**Comment by mgovolt** [comment]
Correct me if I am wrong but there is no fortiweb, fortimail or fortiauthenticator config yet right?

**Comment by enotspe** [comment]
We just uploaded [fortiweb](https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/logstash/42-fortiweb_2_ecs). We have not translated fortimail dataset because [there are no email fields on ECS yet](https://github.com/elastic/ecs/issues/411). I dont think we will cover Fortiauthenticator

**Comment by mgovolt** [comment]
Great thanks. Any update on enSilo? I actually have to start parsing these myself ASAP. I could provide you sample logs to create it, mostly since you would never want to use any code I write.

**Comment by enotspe** [comment]
Ensilo sample logs could definetly help. But it will be better to have the full dataset, similar to a Log Reference Guide

**Comment by sharckerCol** [comment]
Could you put the yml files on the translate  filters? 

filter {

    if [observer][ip] {
        ############### OBSERVER #####################
        translate {
            field => "[observer][ip]"
            destination => "[obs_org_csv]"
            dictionary_path => **"/etc/logstash/host_org.yml"**
            fallback => "default_obs_org_csv"
        }

**Comment by enotspe** [comment]
Hi @sharckerCol , we have uploaded the dictionaries.

**Comment by enotspe** [comment]
dictionaries have been deprecated 4c407060a3f121c968cc6c8fd58967dc33a0c8e9

just the one for fortiweb_attack_logid is left
