### ISSUE TITLE
Question: How to deploy it on my  ELK ?

### ISSUE THREAD

**Issue by asrocha** [enotspe/fortinet-2-elasticsearch#22]
Hi, 
I m not a ELK, specialist ! 
I trying use it in my ELK, but I can t install.
There is a help of where I put each file ?

**Comment by enotspe** [comment]
Hi @asrocha ,

You first have to deploy (or install) Elasticsearch (and Kibana). I use Elastic Cloud, so I didn´t have to install anythingh really.
Then, you have to install Logstash. I normally install it on a Centos sever, it is pretty straighforward actually. You can follow this [link](https://www.elastic.co/guide/en/logstash/current/installing-logstash.html#_yum) for it. There are some recomendations I would suggest:

1. Check firewall rules on your server. This is pretty basic but I can give you a hard time if you forget to open the ports you use for ingesting traffic.
2. Configure your env variable in case you can your logstash hostname on your logs (I manage serveral logstash, so it comes in handy):
  add HOSTNAME="myhostname" to /etc/default/logstash when running [logstash as a service](https://github.com/elastic/logstash/issues/9007)
3. Increase your heap: on jvm.options files inside /etc/logstash, you should change those values
-Xms1g
-Xmx1g
If you use a dedicated server, you can assing 40% of RAM to your heap, considerar that heap could not go higher than 8GB. However I got a logstash where I haven´t tweaked this value and is performing great.
4. Configure your logstash.yml. I manage my pipelines from [Kibana](https://www.elastic.co/guide/en/logstash/current/logstash-centralized-pipeline-management.html), so basically here I just put all the pipelines.id I want my logstash to run.

That´s pretty much it. I will also remmend you suscribe to the Elastic slack channel. I have found great advise there as well. My knowledge is on Fortinet, not ES, so we are all learning on this ES journey.

**Comment by enotspe** [comment]
Readme has been updated with detailed instructions
