### ISSUE TITLE
Question: FortiAnalyzers?

### ISSUE THREAD

**Issue by WinterLily** [enotspe/fortinet-2-elasticsearch#25]
Can this deployment pull from FortiAnalyzer syslog feeds or is this only possible from a FortiGate? 

We have multiple FortiGates all connected to a FortiAnalyzer, so we'd like to run a single feed for all gateways.

**Comment by enotspe** [comment]
Yes indeed. But some modifications have to be made. Basically the problem with FAZ is the timezone field, which comes in a different format than FGT. Actually, I am ingesting Forticlient logs through a relay on FAZ, just like you propose.

What you will need to do is delete that [if](https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/logstash/30-kv_syslog#L31) so `tz` will never be considered, `timestamp` should be built directly from `date` and `time` like we do for [6.0](https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/logstash/30-kv_syslog#L40)

**Comment by enotspe** [comment]
I have added support for FAZ relay.

https://github.com/enotspe/fortinet-2-elasticsearch/commit/d1d352c301f025634985e8a94a24db04b20654d1
