### ISSUE TITLE
Can't import dashboards

### ISSUE THREAD

**Issue by scfigg** [enotspe/fortinet-2-elasticsearch#26]
I've downloaded the raw NDJSON files, and when going into the UI - Stack Management - Kibana - Saved Objects --> Import, I get "Sorry, there was an error. The file could not be processed". I've tried it with all 4 of the NDJSON files on the github repository. I'm coming from Palo Alto to Fortinet, so I'd love to have pre-filled in dashboards that I can look at and tear apart to see how it works.

Any suggestions?

Thank you

**Comment by enotspe** [comment]
I will be closing this issue so we can continue on #27
