### ISSUE TITLE
Can't import dashboards

### ISSUE THREAD

**Issue by scfigg** [enotspe/fortinet-2-elasticsearch#27]
I've downloaded the raw NDJSON files, and when going into the UI - Stack Management - Kibana - Saved Objects --> Import, I get "Sorry, there was an error. The file could not be processed". I've tried it with all 4 of the NDJSON files on the github repository. I'm coming from Palo Alto to Fortinet, so I'd love to have pre-filled in dashboards that I can look at and tear apart to see how it works.

Any suggestions?

Thank you

:edit: for clarification - I'm on 7.9.0 for the whole ELK stack.

**Comment by enotspe** [comment]
Not really sure what could be wrong. Do you have permissions for modifyin objects on Kibana?? (It might be a silly question, but it does not hurt to double check) 

I would suggest you open the ndjosn and replace `kibana.supra.compe` for whatever domain you got and then try upload it again. Altough this has not been a problem in the past, maybe something has change on 7.9.

**Comment by scfigg** [comment]
Yeah, I'm using the default installation on Windows. I can modify saved objects from what I can tell. I tried modifying the file with my IP of my ELK stack in place of that string above, and i get the same error. How can I get debug logs on it to provide you with?

**Comment by enotspe** [comment]
Not really sure how could debugging be done. I will do some testing to try to recreate the issue.

**Comment by enotspe** [comment]
@scfigg I would like to send you a couple of viz, so you can try to load them. Could you provide some contact info, or you can reach out on [discord](https://discord.gg/9qn4enV)

**Comment by scfigg** [comment]
I joined the discord channel if you want to send a message to me on there.

**Comment by enotspe** [comment]
based on our conversation, the problem was that index-templates were not loaded. I will be leaving this issue open until I migrate/add datastreams support, so everythingh will be wrapped up for easier use.

**Comment by enotspe** [comment]
Readme has been updated with detailed instructions. Datastreams are supported now.
