### ISSUE TITLE
Integración

### ISSUE THREAD

**Issue by SecurityLogic** [enotspe/fortinet-2-elasticsearch#28]
@enotspe Excelente proyecto, estamos revisando para un tema académico, te comento que estoy intentando hacer las pruebas de tu proyecto, de la información ofrecida en el issue de instalación la arquitectura corresponte a un colector Logstash local y una Elastic + Kibana Cloud.

He seguido las recomendaciones, pero aún no puedo hacer funcionar el colector con los pipelines (aparentemente me faltan plugins). Por favor me podrías ayudar con los plugins que se deben instalar en el colector y las ubicaciones de los archivos (hearbets, index, ingest, MIBs).

Aprecio mucho tu tiempo y ayuda.

**Comment by enotspe** [comment]
@SecurityLogic por favor no te olvides de subir el video de la implementación que hicimos para que los demás puedan ver el proceso.
