### ISSUE TITLE
Dictionary YAML files?

### ISSUE THREAD

**Issue by aes512** [enotspe/fortinet-2-elasticsearch#3]
Can you provide some examples of each of the dictionaries?

**Comment by pzmq** [comment]
@hoat23 any updates on this matter?

Btw thank you for providing this. It is very helpfull

**Comment by enotspe** [comment]
Hi @pzmq . We have uploaded dictionaries 👍

**Comment by 2Dman** [comment]
i'm missing a dictionary: drop_networks.yml file ?

**Comment by pzmq** [comment]
> 
> 
> i'm missing a dictionary: drop_networks.yml file ?

Sorry, yh, i should've mentioned, but as i dont need the drop pipeline i never used that dictionary. 

"All logs are garbage, until someone comes complaining and you need them. Then they are GOLD. "

**Comment by enotspe** [comment]
I have just added [drop_networks.yml](https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/dictionaries/drop_networks.yml)

**Comment by enotspe** [comment]
dictionaries have been deprecated 4c407060a3f121c968cc6c8fd58967dc33a0c8e9

just the one for fortiweb_attack_logid is left
