### ISSUE TITLE
checking installation

### ISSUE THREAD

**Issue by AlexProfi** [enotspe/fortinet-2-elasticsearch#30]
Hello
How to check that everything right with installation?
I import all dashboards to kibana and 
make put requests to import templates for ecs-* and -fortigate-
configure syslog-ng to transfer data to elastic with names that are expected from dashboards
this is part of json message that generates syslog-ng

`{"url":{"full":""},"source":{"user":{"email":""},"port":"62945","packets":"1","nat":{"port":"62945","ip":"185.183.174.41"},"mac":"64:31:50:37:fc:59","ip":"10.9.0.206","domain":"","bytes":"52"},"rule":{"uuid":"540e8a82-28a4-51ea-4ed6-a35f5b0063df","ruleset":"traffic","name":"","id":"23","category":"forward"},"observer":{"serial_number":"FG100D3G12801312","name":"FORTI_111","ingress":{"interface":{"role":"lan","name":"9 VLAN"}},"egress":{"interface":{"role":"wan","name":"wan2"}}},"network":{"iana_number":"6","application":""},"message":"","log":{"level":"notice"},"host":{"vendor":"HP","type":"","os":{"version":"7","name":"Windows","family":""},"name":"","mac":"64:31:50:37:fc:59","ip":"10.9.0.206"},"fortios":{"service":"tcp/29622"}}`

but there is no in dashboards why?
![Screenshot_2021-02-11_17-16-10](https://user-images.githubusercontent.com/5154879/107648475-6ecc3f80-6c8d-11eb-93a6-e542c475752b.png)

**Comment by AlexProfi** [comment]
![Screenshot_2021-02-11_17-25-59](https://user-images.githubusercontent.com/5154879/107649693-c6b77600-6c8e-11eb-81c1-35d0fca0bcd9.png)
![Screenshot_2021-02-11_17-25-30](https://user-images.githubusercontent.com/5154879/107649697-c7500c80-6c8e-11eb-84c5-bd0c4a7729a0.png)
also i try to see what in dasboards while edit and it shows actual data
but when exit edit mode the panels is blank

**Comment by AlexProfi** [comment]
I resolve it by disable filters at top))

**Comment by enotspe** [comment]
the problematic fields are `srcintfrole` and `dstintfrole`, which has to be configured on firewall. I suggest you only disable those ones

**Comment by AlexProfi** [comment]
Thanks, I forget to add it in result json they were with prefix fortigate.
did you try to port your logstash config 40-ecs-frotigate to syslog-ng config?
there are many conditions syntax by type . syslog-ng use another syntax and don't support conditions

**Comment by enotspe** [comment]
There are no plans for using syslog-ng. Our plans are to split indices by type and sum up everythingh on datastreams.

Something like:

logs-fortinet.fortigate.traffic-space-000001
logs-fortinet.fortigate.utm-space-000001
logs-fortinet.fortigate.event-space-000001

**Comment by AlexProfi** [comment]
and you plan to modify dashboards?

**Comment by enotspe** [comment]
yes, of course!

**Comment by enotspe** [comment]
Readme has been updated with detailed instructions. Dashboards have been updated
