### ISSUE TITLE
deployment to my ELK stack

### ISSUE THREAD

**Issue by azxqw** [enotspe/fortinet-2-elasticsearch#32]
Hi all,
I'm having some trouble understanding how to deploy your configurations to my ELK. 
There are features here that I havent used and im kinda losing my way around all the conf files
any chance someone could provide an explanation as to how to put all the confs, pipelines and mibs on my logstash?
thanks

**Comment by enotspe** [comment]
Hi @azxqw , feel free to jump into our Discord channel. We will be very happy to help out.
