### ISSUE TITLE
Help with Issues

### ISSUE THREAD

**Issue by akrog79** [enotspe/fortinet-2-elasticsearch#47]
Hello, first of all congrats for the solution, it's amazing!

I'm trying to deploy it but I get some errors:

[ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:syslog-fortinet-common_ecs-output, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:234:in `initialize'", "org/logstash/execution/AbstractPipelineExt.java:168:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:48:in `initialize'", "org/jruby/RubyClass.java:911:in `new'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:50:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:386:in `block in converge_state'"]}

[WARN ][org.logstash.plugins.pipeline.PipelineBus][syslog-fortinet-fortigate_2_ecsv2][3f0de7dc0df9b79955e21fe0954f4615326ef0e002822839720b6337d266eb85] Attempted to send event to 'syslog-fortinet-common_ecs-output' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.

Can you help my with this errors?

Thanks!

**Comment by enotspe** [comment]
Check that you copy it correctly. You might be missing the "i" of "input"

Line 1, column 1 error
