### ISSUE TITLE
I can't discover Fortigate log

### ISSUE THREAD

**Issue by ginobyte** [enotspe/fortinet-2-elasticsearch#49]
HI, I'm newby of ELK Stack, I'm working now with FortiManager&FortiAnalyzer, and I'm courious to try  FortiDragon :) , I've started with Bitnami distribution ELK stack. I've followed your guide step-by-step , I stopped and unistalled Filebeat, I' see the syslog traffic incoming from UDP port but I don't discover any data stream Fortinet Log ...Any Idea ??

Thanks for your help....if you need to see some configurations file or log I can show you..it's a Lab environnement.

**Comment by enotspe** [comment]
Hello, 

FortiDragon uses differente indeces than Filebeat. If you have the default config of FortiDragon, then you should have a Data View named logs-fortinet.fortigate*.

**Comment by enotspe** [comment]
we have a new and much simpler [installation](https://github.com/enotspe/fortinet-2-elasticsearch?tab=readme-ov-file#installation) procedure
