### ISSUE TITLE
Logstash Error on field data

### ISSUE THREAD

**Issue by pzmq** [enotspe/fortinet-2-elasticsearch#5]
Is it realy necessary to change the mappings for them to  be "Field Data : True"??
Why aren't the dashboards using the keywords?
![image](https://user-images.githubusercontent.com/1643249/78367565-33b3a700-75ba-11ea-8a2e-84329dab686b.png)

**Comment by enotspe** [comment]
Hi @pzmq. We have uplaoded fortigate template, so you should not get that error. Basically, except the fields specified on the template, all fields should be keyword
