### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by nuno-andre** [enotspe/fortinet-2-elasticsearch#51]
In `/logstash/pipelines.yml` there is a reference to a config file which is not found in `/logstash/conf.d`:

```yaml
- pipeline.id: syslog-fortinet-fortigate_2_ecs
  path.config: "/etc/logstash/conf.d/syslog-fortinet-fortigate_2_ecs.conf"
```

It comes from f7203d401

Could it be [this one](https://github.com/enotspe/fortinet-2-elasticsearch/blob/0a3c0fa5549242ded9a6273427dca266a636a9fe/logstash/conf.d/fortigate_2_ecs.conf)?

**Comment by enotspe** [comment]
Just comment out that reference. It is not needed any more. I will update pipelines.yml
