### ISSUE TITLE
Field and Document level security Integration 

### ISSUE THREAD

**Issue by JesseNordin** [enotspe/fortinet-2-elasticsearch#56]
Hello

I'd like to ask if there are any future plans on the roadmap to integrate Field and Document level security for the data ingested by Fortinet-2-elasticsearch. We have a UTM with many different customer integrations, the only differentiator being the Security Profile names. 

I have seen with some of the dashboards it's possible to filter by these security profiles or even the subnets allocated to a customer but I would like to expand on that and create a "Space" for that customer granting read only access to the needed Indices.  I have asked the elasticsearch team on how one can prevent a user from seeing data that's not relevant to them and I was shown the below: 

![image_720](https://github.com/enotspe/fortinet-2-elasticsearch/assets/149584316/9d39c659-12bd-40b9-97c1-e8bd01e33f5b)

I have however noticed that this option (Grant Access to specific fields) does not exist in our ELK Stack, I'd like to clarify if this is due to the way the data is ingested or is this due to our subscription level (Currently Free and open Basic) ? 

General Info: 
Fortigate Version: v7.0.11
ELK Stack Version: 8.12.1

**Comment by enotspe** [comment]
you can copy the utmprofile value to namespace.

That is what is cool about all the code being open, you can tweak to your case, which is very very specific. Normally I have seen the use of VODMs for partioning clients.

`mutate { replace => { "[data_stream][namespace]" => "%{[fgt][profile]}" } }`

**Comment by JesseNordin** [comment]
Sorry, I'm not entirely sure that I follow, 

Are you saying that we could apply this mutation on a per "Space" level while specifying the space and associated fgt profile ?  

Or would this be globally applied so that elk can pick up the fgt profiles within the data streams to allow for the options of grant access to specific fields etc
