### ISSUE TITLE
Output pipeline not working properly

### ISSUE THREAD

**Issue by pzmq** [enotspe/fortinet-2-elasticsearch#6]
Sorry if i'm mistaken, but for what i'm seeing, the line

`output{
        pipeline {
            send_to => "drop" 
        }`

isn't working properly, I forwarded a log from a host that isn't on the "host_org.yml" dictionary
and supposedly, the order should be 

10-input_syslog.conf -> 20-observer_enrichment.conf -> 70-drop.conf -> 80-output.conf

But according to the line 
`[2020-04-06T12:41:41,278][DEBUG][logstash.util.decorators ][main] filters/LogStash::Filters::Mutate: adding value to field {"field"=>"[ecs][version]", "value"=>["1.2.0"]}` and by the debug that made, the tag is added in the file `21-snmp_cpu_fortigate_2_ecs.conf`

So, by the debug i've made, instead of going through the pipelines, logstash is going through the file names.

DEBUG LOGS:

![image](https://user-images.githubusercontent.com/1643249/78556529-0a3b8b00-7807-11ea-93bf-31bfbd317a83.png)

PS: For the porpuse of putting the logs in here i changed the field `host` to another IP in the `10-input_syslog.conf` file withe the following line:
`
        add_field => {"host" => "10.0.1.254"}`

**Comment by whataboutpereira** [comment]
I may be wrong, but I think you need to add the pipelines to Logstash pipelines for it all to work as intended.

**Comment by pzmq** [comment]
how's so? could u provide an example of a config for one of the pipelines.

**Comment by pzmq** [comment]
Srry for the dumb question ofc... thank you
