### ISSUE TITLE
Questions - Fortigate - SysLog - CEF?

### ISSUE THREAD

**Issue by nicpenning** [enotspe/fortinet-2-elasticsearch#8]
Hi,

First of all, this looks really good and appreciate all the efforts you have gone through to make it this far! I am very interested to ingest Fortinet logs into ElasticSearch.

1st Question: Do you have a slack, gitter, or other project communication channel to ask questions like these and help with the project?

2nd Question: Does the input for the SysLog need to be the regular format or in CEF? I have started down this path with FileBeat and CEF to ingest all the CEF fields to something but wasn't sure how this project was going about that.

3rd Question: Is there any other documentation to get this setup? I can fumble through and pick different pieces and parts but I wanted to make sure there wasn't anything available that made this process easier.

Thanks and keep up the good work!

**Comment by enotspe** [comment]
Hi @nicpenning 

About your questions:

1 We dont have any other communication channel besides github yet. 

2 Regular syslog, no CEF. ECS is the new CEF.

3 Not really, this all the documentation we have so far. We will try to give more details. Basically, what you need to do is: 
* Set up your ES cluster. 
* Load pipelines to logstash. 
* Build you dictionaries for enrichment. This is kind of optional, only if you want enrichments on your logs, you should do this.
* Load dashboards and templates to Kibana
* Stream your syslog from your firewalls to your logstash IP.

It should be pretty straight forward if you have some experience with ES. 

We would be able to help as well if you need some extra hand.

**Comment by nicpenning** [comment]
Thanks for the quick response! I have some follow up questions that may not be suited here, how can I get a hold of you?

**Comment by enotspe** [comment]
Just send me an email

Enotspe@gmail.com

**Comment by fpompermaier** [comment]
What I do is to send Fortinet CEF to a filebeat (that performs some basic ECS alignment), with just a little modification of the beat conf to properly set the observer ip (becuase of https://github.com/elastic/beats/issues/15774). Then I just rename some field and that's it. If you follow the syslog way you have to do an extra work on the patterns..so I prefer to use the cef module. It only needs to be more aligned to ECS
